repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

      - id: nbqa-black
        name: nbqa-black
        entry: nbqa black
        language: system

      - id: nbqa-isort
        name: nbqa-isort
        entry: nbqa isort
        language: system
      